### ISSUE TITLE
[RELEASE] AWS 배포

### ISSUE THREAD

**Issue by tmdtmdqorekf** [kookmin-sw/capstone-2024-17#13]
## 어떤 기능인가요?

> 서버와 DB를 AWS에 배포하는 기능입니다.

## 작업 상세 내용

- [ ] TODO 서버 배포 (dockerfile 작성해서 docker 이미지로 말아서 배포)
- [ ] TODO DB 배포

**Comment by hyeesw** [comment]
- 13번 브랜치 commit 내용이 좀 꼬여서 바로 master 브랜치에 이어서 작업했습니다.
- master 브랜치에 베포 관련 코드 올렸고, 서버 문제없이 실행되는거 확인해서 이슈 닫습니다!
- 서버 주소는 Notion 메인 페이지에 올려뒀습니다
