### ISSUE TITLE
[FEATURE] Redis 사용자 위치 값 저장

### ISSUE THREAD

**Issue by tmdtmdqorekf** [kookmin-sw/capstone-2024-17#19]
## 어떤 기능인가요?

> Redis에서 사용자 위치 값을 저장하는 기능입니다.

## 작업 상세 내용

- [ ] TODO 사용자 위치 값 저장
- [ ] TODO 테스트

**Comment by hyeesw** [comment]
이슈 39번 내용과 겹쳐서 종료합니다.
